### ISSUE TITLE
Migrate all post-OS changes to the Modpack.

### ISSUE THREAD

**Issue by DaloLorn** [OpenSRProject/OpenStarRuler-Data#1]
This repository's purpose is to serve as a source of unmodified, Steam-compatible data for a basic Star Ruler 2 installation. As such, it should not be changed from the original source dump... which it already has, unfortunately.

The changes need to be identified and migrated into the Modpack as soon as possible.

**Comment by DaloLorn** [comment]
This is now done.

**Comment by Skeletonxf** [comment]
Shaders are completely client side, I think we should be willing to include crash preventing fixes like the ringworld fix in this repository rather than force users to obtain them via the modpack or manually porting the fix.

The modpack after all is not compatible with the majority of mods

**Comment by DaloLorn** [comment]
... Point taken. Shaders are also extremely tiny, so the redundant download is also not an issue.
